variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://docker:2375
  GIT_SUBMODULE_STRATEGY: recursive
  CONTAINER_DEV_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

# Pipeline steps list
stages:
  - build
  - deploy

# Build step
build:
  stage: build
  image: docker:git
  only: [master]
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/$CI_PROJECT_PATH .
    - docker tag registry.gitlab.com/$CI_PROJECT_PATH registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_SHA
    - docker push registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_SHA

# Deploy step
deploy:
  stage: deploy
  image: google/cloud-sdk
  only: [master]
  environment:
    name: prod
  script:
    - echo "$SERVICE_ACCOUNT_KEY" > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud config set project zuoyou-456ad
    - gcloud config set container/cluster zuoyou-ci-cluster
    - gcloud config set compute/zone us-central1-a
    - gcloud container clusters get-credentials zuoyou-ci-cluster --zone us-central1-c
    - kubectl run zuoyou-backend --image=registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_SHA
    - kubectl expose deployments zuoyou-backend --port=80 --target-port=9000 --type=LoadBalancer


