# Config file for Gitlab Continuous Integration pipeline
# The pipeline is divided in a build step and a deployment step
#
# During the build, the docker container is built and registered in Gitlab's container registry
# During the deployment, there is an authentication using a GCP auth token,
# then the kubernetes.yml is executed to create the Deployment Kubernetes Replication Controller.
#
# This file require the following environment variable, configured through the Gitlab UI (repo -> Settings -> CI -> Environment Var) :
#   - $SSH_DEPLOY_KEY : SSH private key to the server
#
# Written by Rémy HIDRA, Curios, 2020.


variables:
  DEPLOYMENT_SERVER_IP: api.zuoyoubycurios.com

stages:
  - deploy

deploy:
  stage: deploy
  image: gitlab/dind:latest
  only: [master]
  script:
    - mkdir -p ~/.ssh/
    - echo -e $SSH_DEPLOY_KEY > ~/.ssh/rsa_key
    - chmod 600 ~/.ssh/rsa_key
    - ssh-keyscan -H $DEPLOYMENT_SERVER_IP >> ~/.ssh/known_hosts
    - ssh -i ~/.ssh/rsa_key api@api.zuoyoubycurios.com "cd zuoyou-backend; git pull; docker-compose build; docker-compose up -d"
