# Config file for Gitlab Continuous Integration pipeline
#
# TODO: Add a step for testing
#
# This file require the following environment variable, configured through the Gitlab UI (repo -> Settings -> CI -> Environment Var) :
#   - $SSH_DEPLOY_KEY : SSH private key to the server
#
# Written by Rémy HIDRA, Curios, 2020.


variables:
  DEPLOYMENT_SERVER_IP: api.zuoyoubycurios.com

stages:
  - deploy

deploy:
  stage: deploy
  image: gitlab/dind:latest
  only: [master]
  script:
    - mkdir -p ~/.ssh/
    - echo -e "$SSH_DEPLOY_KEY" > ~/.ssh/rsa_key
    - chmod 700 ~/.ssh
    - chmod 600 ~/.ssh/rsa_key
    - ssh-keyscan -H $DEPLOYMENT_SERVER_IP >> ~/.ssh/known_hosts
    #- ssh -i ~/.ssh/rsa_key api@api.zuoyoubycurios.com "cd clapback-backend; git pull; docker-compose build; docker-compose up -d"
