variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://localhost:2375
  GIT_SUBMODULE_STRATEGY: recursive
  CONTAINER_DEV_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

# Pipeline steps list
stages:
  - build
  # - deploy

# Build step
build:
  stage: build
  image: docker:stable
  services:
    - docker:stable-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/$CI_PROJECT_PATH .
    - docker tag registry.gitlab.com/$CI_PROJECT_PATH registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_SHA
    - docker push registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_SHA
  only:
    - master

