version: "3"

services:
  api:
    container_name: zuoyou-backend
    restart: always
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    healthcheck:
      test: ['CMD', "echo 'db.runCommand(\"ping\").ok' | mongo localhost:27017/test --quiet"]
    ports:
      - "27017:27017"
    command: mongod --noauth
    volumes:
      - ./data-node:/data/db
