version: "3"

services:
  api:
    container_name: zuoyou-backend
    image: node:11
    restart: always
    build: .
    ports:
      - "9000:9000"
    command: bash -c "npm install && npm run dev"
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    depends_on:
      - mongodb
    networks:
      - webappnetwork

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    command: mongod --noauth
    volumes:
      - ./data-node:/data/db
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge
