version: "3"

services:
  api:
    container_name: zuoyou-backend
    restart: always
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - mongo
    volumes:
      - ./public:./public
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    healthcheck:
      test: ['CMD', "echo 'db.runCommand(\"ping\").ok' | mongo localhost:27017/test --quiet"]
    ports:
      - "27017:27017"
    command: mongod --noauth
    volumes:
      - ./data-node:/data/db

  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx
    # TODO: Remove --staging option when prod clean
    command: certonly --email zuoyoucurios@gmail.com --agree-tos --no-eff-email --staging -d api.zuoyoubycurios.com

volumes:
  certbot-etc:
  certbot-var:
