# Define the containers to have a functionnal backend API for the Clapback app
# Before starting first, to make nginx starts in HTTPS, you need to run init-letsencrypt.sh

version: "3"

services:
  # Main node/express REST server
  api:
    container_name: clapback-backend
    restart: always
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - mongo
    volumes:
      - ./public:/usr/app/public
    links:
      - mongo

  # Mongo DB, mounted on 27017
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data-node:/data/db

  # End point of the server
  nginx:
    container_name: nginx
    restart: always
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./public:/var/public
    depends_on:
      - api
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # Automate certificate renewal
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    # Renew the certificate every 12h
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  certbot-etc:
  certbot-var:
