version: "3"

services:
  api:
    container_name: zuoyou-backend
    restart: always
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - mongo
    volumes:
      - ./public:/usr/app/public
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    healthcheck:
      test: ['CMD', "echo 'db.runCommand(\"ping\").ok' | mongo localhost:27017/test --quiet"]
    ports:
      - "27017:27017"
    command: mongod --noauth
    volumes:
      - ./data-node:/data/db

  nginx:
    container_name: nginx
    restart: always
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  certbot-etc:
  certbot-var:
