version: "3"

services:
  api:
    container_name: zuoyou-backend
    build: .
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - .:/api
      - /node_modules
    depends_on:
      - mongodb
    networks:
      - webappnetwork

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge
