---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zuoyou-backend
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web

  # Pod template
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        image: _CONTAINER_IMAGE_
        # Environment variable to load secrets
        # See .prod-secrets.yaml uncommitted secret file
        env:
          - name: NODE_ENV
            valueFrom:
              secretKeyRef:
                name: zuoyou-backend
                key: NODE_ENV
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: zuoyou-backend
                key: PORT
          - name: HOST_URL
            valueFrom:
              secretKeyRef:
                name: zuoyou-backend
                key: HOST_URL
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: zuoyou-backend
                key: SESSION_SECRET
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: zuoyou-backend
                key: JWT_SECRET
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: zuoyou-backend
                key: MONGODB_URI
          - name: SMTP_HOST
            valueFrom:
              secretKeyRef:
                name: zuoyou-backend
                key: SMTP_HOST
          - name: SMTP_PORT
            valueFrom:
              secretKeyRef:
                name: zuoyou-backend
                key: SMTP_PORT
          - name: SMTP_USER
            valueFrom:
              secretKeyRef:
                name: zuoyou-backend
                key: SMTP_USER
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zuoyou-backend
                key: SMTP_PASSWORD
